name: flutter_news_app_mobile_client_full_source_code
description: Complete, production-ready source code for a feature-rich Flutter news app mobile client.
version: 1.10.0
publish_to: none
repository: https://github.com/flutter-news-app-full-source-code/flutter-news-app-mobile-client-full-source-code
homepage: https://flutter-news-app-full-source-code.github.io/docs/
documentation: https://flutter-news-app-full-source-code.github.io/docs/getting-started/
issue_tracker: https://github.com/flutter-news-app-full-source-code/flutter-news-app-mobile-client-full-source-code/issues
funding:
  - https://github.com/sponsors/flutter-news-app-full-source-code
topics:
  - flutter
  - flutter-full-app
  - flutter-news-app
  - flutter-news-app-mobile-client
  - flutter-news-app-source-code
screenshots:
  - description: The flutter news app full source code dark logo.
    path: assets/logo/flutter-news-app-full-source-code-dark-logo.png
  - description: The flutter news app full source code light logo.
    path: assets/logo/flutter-news-app-full-source-code-light-logo.png

environment:
  sdk: ^3.9.0

dependencies:
  auth_api:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-api.git
      ref: v1.0.1
  auth_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-client.git
      ref: v1.0.1
  auth_inmemory:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-inmemory.git
      ref: 7fc38f09b941f2bbae3d7c9f21ff6848d3d9d258
  auth_repository:
    git:
      url: https://github.com/flutter-news-app-full-source-code/auth-repository.git
      ref: v1.0.1
  bloc: ^9.0.1
  bloc_concurrency: ^0.3.0
  collection: ^1.19.1
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.3.1
  data_api:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-api.git
      ref: v1.0.1
  data_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-client.git
      ref: v1.0.1
  data_inmemory:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-inmemory.git
      ref: v1.1.0
  data_repository:
    git:
      url: https://github.com/flutter-news-app-full-source-code/data-repository.git
      ref: v1.0.1
  device_preview: ^1.2.0
  equatable: ^2.0.7
  firebase_analytics: ^12.1.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.2
  flutter_bloc: ^9.1.1
  flutter_inappwebview: 6.1.5
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  google_mobile_ads: ^6.0.0
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.0.1
  in_app_purchase: ^3.2.3
  in_app_review: ^2.0.11
  intl: ^0.20.2
  js_interop: ^0.0.1
  kv_storage_service:
    git:
      url: https://github.com/flutter-news-app-full-source-code/kv-storage-service.git
      ref: v1.0.1
  kv_storage_shared_preferences:
    git:
      url: https://github.com/flutter-news-app-full-source-code/kv-storage-shared-preferences.git
      ref: v1.0.1
  logging: ^1.3.0
  meta: ^1.16.0
  mixpanel_flutter: ^2.4.4
  onesignal_flutter: ^5.3.4
  package_info_plus: ^9.0.0
  pinput: ^5.0.1
  pub_semver: ^2.2.0
  share_plus: ^11.1.0
  stream_transform: ^2.1.1
  timeago: ^3.7.1
  ui_kit:
    git:
      url: https://github.com/flutter-news-app-full-source-code/ui-kit.git
      ref: v1.0.1
  url_launcher: ^6.3.1
  uuid: ^4.4.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/

flutter_launcher_icons:
  image_path: assets/logo/flutter-news-app-full-source-code-dark-logo.png
  android: "launcher_icon"
  min_sdk_android: 21
  web:
    generate: true
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#212121"
  image: assets/logo/flutter-news-app-full-source-code-dark-logo.png
  image_dark: assets/logo/flutter-news-app-full-source-code-light-logo.png
  android: true
  ios: true
  web: true

dependency_overrides:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 80fbc87e850b5ace5da8fe4dde490a45b66db18e
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git
      ref: v1.1.0
